// The recorded demo script. Every number here is what the real code produces:
// backtest.run() deltas, canary.expected_cost(), constitution.clamp() notes,
// beta-posterior profiles over the five seeded episodes. No live calls yet.
const PEOPLE = {
  alex:   { name: "Alex",   color: "#0e7c66", initials: "A" },
  sam:    { name: "Sam",    color: "#b4532a", initials: "S" },
  priya:  { name: "Priya",  color: "#5b4bbd", initials: "P" },
  jordan: { name: "Jordan", color: "#1d6fb8", initials: "J" },
  maya:   { name: "Maya",   color: "#a8347a", initials: "M" },
  flake:  { name: "Flake",  color: "#0b5d4f", initials: "F" },
};

const V1 = {
  rules: [],
  guardrails: { max_nonrefundable_exposure_usd: 0, max_auto_spend_usd: 0, min_expected_attendance_ratio: 0.8, min_confidence: 0.85 },
  tool_permissions: { book: { refundable: "auto", non_refundable: "ask" }, request_money: { default: "ask", auto_for: [] }, cancel_booking: "ask" },
  context_policy: { similar_plans_k: 3, notes_per_person: 2, include_recent_bails: true },
};

const BASE_PROFILES = [
  ["sam",    5, 4, 0.71, 0.92, 0.67, 457],
  ["priya",  5, 0, 0.14, 0.32, 0.14, 771],
  ["jordan", 5, 0, 0.14, 0.32, 0.86, 771],
  ["maya",   5, 2, 0.43, 0.66, 0.20, 614],
];
const RETRO_PROFILES = [
  ["sam",    6, 5, 0.75, 0.93, 0.67, 438],
  ["priya",  6, 0, 0.13, 0.28, 0.13, 781],
  ["jordan", 6, 0, 0.13, 0.28, 0.88, 781],
  ["maya",   6, 2, 0.38, 0.61, 0.17, 644],
];
const profTable = (rows) => ({
  kind: "table",
  head: ["friend", "n", "bails", "P(flake)", "upper 90%", "pays late", "Flake Score"],
  rows: rows.map(([p, n, k, m, u, l, s]) => [PEOPLE[p].name, n, k, m.toFixed(2), u.toFixed(2), l.toFixed(2), s]),
});

// ---- beats -------------------------------------------------------------
// event: { node, lane, kind, label, detail?, chat?, approval? }
// kind drives the accent: db | model | allow | modify | ask | deny | info | promote | reject
const BEATS = [
  {
    id: "reset",
    title: "Reset / baseline",
    subtitle: "Five historical plans restored, v1 on probation",
    policy: { label: "v1", status: "probation" },
    events: [
      { node: "memory", kind: "db", label: "episodes.insert_many — 5 resolved plans + embeddings",
        detail: { kind: "table", head: ["plan", "title", "day", "share", "bailed", "lost"], rows: [
          ["ep_001", "Pizza night", "weekday", "$20", "sam, maya", "$40"],
          ["ep_002", "Karaoke Friday", "weekday", "$40", "sam", "$40"],
          ["ep_003", "Ski trip", "weekend", "$150", "sam", "$150"],
          ["ep_004", "Sunday brunch", "weekend", "$30", "—", "$0"],
          ["ep_005", "Comedy show", "weekday", "$35", "sam, maya", "$70"],
        ], note: "5 documents written · $300 lost to bails before Flake existed" } },
      { node: "risk", kind: "db", label: "risk_profiles — baseline posteriors from 5 episodes",
        detail: profTable(BASE_PROFILES) },
      { node: "policy", kind: "info", label: "harness_versions — taco-council:v1 active (probation)",
        detail: { kind: "json", title: "v1 policy", value: V1,
          note: "No rules. Zero exposure, zero unasked spend: every money action is a question for Alex." },
        chat: { from: "system", text: "Taco Council · Alex, Sam, Priya, Jordan, Maya" } },
      { node: "policy", kind: "info", label: "baseline ready",
        chat: { from: "flake", text: "Connected. I've read 5 past plans — $300 lost to bails. I'm on v1: I can't spend anything without asking you." } },
    ],
  },
  {
    id: "taco",
    title: "Taco Tuesday",
    subtitle: "$25 a head under v1 — every booking needs Alex",
    policy: { label: "v1", status: "probation" },
    events: [
      { node: "memory", lane: "plan", kind: "info", label: "brief received — cost_per_person $25, min_people 3",
        chat: { from: "alex", text: "Taco Tuesday next week? $25 a head, need at least 3 of us." } },
      { node: "memory", lane: "plan", kind: "db", label: "vector search episodes — k=3 (context_policy.similar_plans_k)",
        detail: { kind: "table", head: ["plan", "summary", "score"], rows: [
          ["ep_005", "Comedy show on a weekday, $35 each. Sam and Maya bailed; $70 lost.", "0.89"],
          ["ep_001", "Pizza night on a weekday, $20 each. Sam and Maya bailed; $40 lost.", "0.86"],
          ["ep_002", "Karaoke Friday on a weekday, $40 each. Sam bailed; $40 lost.", "0.81"],
        ], note: "$vectorSearch on episodes.embedding · 3 of 5 returned" } },
      { node: "agent", lane: "plan", kind: "model", label: "agent turn 1 — cache hit → propose_plan",
        detail: { kind: "json", title: "tool call", value: { tool: "propose_plan", day: "2026-10-06", day_type: "weekday", cost_per_person_usd: 25, min_people: 3 },
          note: "LLM cache hit (.llm_cache.sqlite) — no fresh call." } },
      { node: "gate", lane: "plan", kind: "allow", label: "gate: ALLOW propose_plan — within policy",
        detail: { kind: "json", title: "Decision", value: { action: "allow", reason: "within policy", rule_id: null, version_id: "taco-council:v1" },
          note: "v1 has no rules, and propose_plan is auto." } },
      { node: "tools", lane: "plan", kind: "allow", label: "propose_plan → group",
        chat: { from: "flake", card: { title: "Taco Tuesday", lines: ["Tue 6 Oct · El Farolito", "$25 per person", "Need 3 to go ahead"] } } },
      { node: "tools", lane: "plan", kind: "allow", label: "poll_rsvps → 3 yes, 1 no",
        chat: { from: "flake", rsvps: [["sam", "yes"], ["priya", "yes"], ["jordan", "yes"], ["maya", "no"]] } },
      { node: "agent", lane: "plan", kind: "model", label: "agent turn 2 — fresh call → book",
        detail: { kind: "json", title: "tool call", value: { tool: "book", non_refundable_for: ["sam", "priya", "jordan"], refundable_for: [], total_usd: 100 },
          note: "Fresh model call, 1.8s. The model asks for the cheapest booking — all non-refundable." } },
      { node: "gate", lane: "plan", kind: "ask", label: "gate: ASK book — 3 guardrails breached",
        detail: { kind: "reasons", title: "Decision · action=ask · version taco-council:v1", rows: [
          "non-refundable exposure $75 is over the $0 cap",
          "spend $100 is over the $0 auto-spend cap",
          "only 43% confidence that 3 show",
        ], note: "tool_permissions.book.non_refundable = ask, and guardrails only ever escalate." },
        approval: { id: "ap1", tool: "book", question: "Approve book $100 — $75 non-refundable on Sam, Priya, Jordan?" } },
      { node: "tools", lane: "plan", kind: "allow", label: "book → confirmed (approval ap1 on record)",
        chat: { from: "flake", card: { title: "Booked · El Farolito", lines: ["Tue 6 Oct, 7:00pm · table for 4", "$100 charged · $75 non-refundable", "Approved by Alex"], tone: "receipt" } },
        detail: { kind: "json", title: "audit_log", value: { tool: "book", decision: "allow", reason: "within policy (approved)", approval: "ap1", version_id: "taco-council:v1", episode_id: "ep_006" } } },
      { node: "agent", lane: "plan", kind: "allow", label: "finish_plan — ep_006 booked under v1" },
    ],
  },
  {
    id: "tick1",
    title: "Advance 7 days",
    subtitle: "What actually happened",
    policy: { label: "v1", status: "probation" },
    events: [
      { node: "tools", lane: "learn", kind: "info", label: "simulator.tick(7) — seeded per tick",
        chat: { from: "sam", text: "ahh sorry, can't make it tonight 😬" } },
      { node: "outcomes", lane: "learn", kind: "db", label: "episodes.update_one ep_006 — status resolved",
        detail: { kind: "json", title: "outcomes", value: { bailed: ["sam"], showed: ["priya", "jordan"], total_cost_usd: 25, paid_late_days: { jordan: 12, priya: 0 } },
          note: "Sam's $25 was non-refundable: incurred, not recoverable. Jordan paid 12 days late." },
        chat: { from: "system", text: "Plan resolved · 2 of 3 showed · $25 lost · Jordan paid 12 days late" } },
      { node: "risk", lane: "learn", kind: "info", label: "episode 6 available to the next Retro" },
    ],
  },
  {
    id: "retro",
    title: "Run Retro",
    subtitle: "Outcomes → risk → proposal → constitution → backtest → v2",
    policy: { label: "v1", status: "probation" },
    events: [
      { node: "risk", lane: "learn", kind: "db", label: "build_profiles — 6 episodes, posteriors updated",
        detail: profTable(RETRO_PROFILES) },
      { node: "proposal", lane: "learn", kind: "model", label: "underwriter_llm.propose — fresh call",
        detail: { kind: "json", title: "PolicyProposal", value: {
            rules: [
              { type: "book_refundable_for", people: ["sam"] },
              { type: "require_deposit_from", people: ["jordan"] },
              { type: "auto_collect_from", people: ["priya"] },
            ],
            guardrails: { max_nonrefundable_exposure_usd: 500, max_auto_spend_usd: 150, min_expected_attendance_ratio: 0.6, min_confidence: 0.75 },
            auto_book_nonrefundable: true, similar_plans_k: 5,
            rationale: "Sam has bailed on 5 of 6 plans — buy the refundable ticket for Sam only. Jordan always pays, but 5-20 days late: take a deposit up front. Priya has never missed or paid late: collect from Priya automatically.",
          } } },
      { node: "policy", lane: "learn", kind: "deny", label: "constitution.clamp — 2 guardrails pushed back inside the floors",
        detail: { kind: "reasons", title: "constitution_notes", rows: [
          "max_nonrefundable_exposure_usd 500 clamped to 300",
          "max_auto_spend_usd 150 clamped to 100",
        ], note: "FLOORS are code, not a promise. cancel_booking stays ask whatever the Retro proposes." } },
      { node: "backtest", lane: "learn", kind: "allow", label: "backtest.run — 6 episodes, delta +$225.00 → ship",
        detail: { kind: "table", head: ["rule", "people", "marginal", "evidence"], rows: [
          ["book_refundable_for", "sam", "+$225.00", "accepted"],
          ["require_deposit_from", "jordan", "$0.00", "51 late days avoided"],
          ["auto_collect_from", "priya", "$0.00", "6 on-time payments"],
        ], note: "baseline $325.00 → proposed $100.00 · accepted 3, rejected 0 · replayed against real episode outcomes." } },
      { node: "policy", lane: "learn", kind: "promote", label: "versions.create → taco-council:v2 status canary",
        detail: { kind: "json", title: "taco-council:v2", value: { status: "canary", parent: "taco-council:v1", created_by: "retro", backtest_delta_usd: 225, rules: 3 },
          note: "A canary judges exactly one plan. get_effective() now returns v2 for the next brief." },
        chat: { from: "flake", text: "Retro done. I've proposed v2 — refundable ticket for Sam, deposit from Jordan, auto-collect from Priya. It saves $225 replayed over our history, so it's on trial for the next plan." } },
    ],
  },
  {
    id: "compare",
    title: "Compare policies",
    subtitle: "versions.diff v1 → v2",
    policy: { label: "v2", status: "canary" },
    events: [
      { node: "policy", lane: "learn", kind: "info", label: "versions.diff taco-council:v1 → taco-council:v2",
        detail: { kind: "diff", rows: [
          ["rules", "0 rules", "3 rules"],
          ["tool_permissions.book.non_refundable", "ask", "auto"],
          ["tool_permissions.request_money.auto_for", "[]", "['priya']"],
          ["guardrails.max_nonrefundable_exposure_usd", "0", "300"],
          ["guardrails.max_auto_spend_usd", "0", "100"],
          ["guardrails.min_expected_attendance_ratio", "0.8", "0.6"],
          ["guardrails.min_confidence", "0.85", "0.75"],
          ["context_policy.similar_plans_k", "3", "5"],
        ], note: "Flattened to dotted keys — only what changed. Both ceilings sit exactly on the constitution floors." } },
    ],
  },
  {
    id: "beach",
    title: "Beach Weekend",
    subtitle: "$120 a head — v2 enters the gate",
    policy: { label: "v2", status: "canary" },
    hero: true,
    events: [
      { node: "policy", lane: "hero", kind: "promote", label: "get_effective() → taco-council:v2 (canary) governs this plan",
        detail: { kind: "json", title: "policy → gate", value: { version_id: "taco-council:v2", status: "canary", rules: ["book_refundable_for[sam]", "require_deposit_from[jordan]", "auto_collect_from[priya]"] },
          note: "This is the loop closing: last week's outcomes are now the rules the gate enforces." },
        chat: { from: "alex", text: "Beach weekend? Saturday, $120 each, need 3." } },
      { node: "memory", lane: "plan", kind: "db", label: "vector search episodes — k=5 (v2 widened context)",
        detail: { kind: "table", head: ["plan", "summary", "score"], rows: [
          ["ep_003", "Ski trip on a Saturday, $150 each. Sam bailed; $150 lost.", "0.91"],
          ["ep_004", "Sunday brunch on a Sunday, $30 each. Nobody bailed; $0 lost.", "0.84"],
          ["ep_006", "Taco Tuesday on a weekday, $25 each. Sam bailed; $25 lost.", "0.78"],
          ["ep_002", "Karaoke Friday on a weekday, $40 each. Sam bailed; $40 lost.", "0.74"],
          ["ep_001", "Pizza night on a weekday, $20 each. Sam and Maya bailed; $40 lost.", "0.71"],
        ], note: "k went 3 → 5 because v2 raised similar_plans_k." } },
      { node: "gate", lane: "plan", kind: "allow", label: "gate: ALLOW propose_plan — weekend, $120, within policy" },
      { node: "tools", lane: "plan", kind: "allow", label: "poll_rsvps → 3 yes, 1 no",
        chat: { from: "flake", rsvps: [["sam", "yes"], ["priya", "yes"], ["jordan", "yes"], ["maya", "no"]] } },
      { node: "agent", lane: "plan", kind: "model", label: "agent turn 2 — cache hit → book",
        detail: { kind: "json", title: "tool call", value: { tool: "book", non_refundable_for: ["sam", "priya", "jordan"], refundable_for: [] } } },
      { node: "gate", lane: "plan", kind: "deny", label: "gate: DENY book — rule r2 require_deposit_from[jordan]",
        detail: { kind: "reasons", title: "Decision · action=deny · rule r2", rows: [
          "call request_money(upfront=True) for jordan before booking",
        ], note: "Jordan's 51 late days last quarter became a hard precondition on booking." } },
      { node: "agent", lane: "plan", kind: "model", label: "agent turn 3 — repairs the call → request_money",
        detail: { kind: "json", title: "tool call", value: { tool: "request_money", person: "jordan", amount_usd: 120, upfront: true } } },
      { node: "gate", lane: "plan", kind: "ask", label: "gate: ASK request_money — jordan not in auto_for",
        detail: { kind: "reasons", title: "Decision · action=ask", rows: ["request_money default is ask; auto_for = ['priya']"],
          note: "v2 learned to trust Priya automatically. Jordan still goes to Alex." },
        approval: { id: "ap2", tool: "request_money", question: "Approve request_money — $120 deposit from Jordan, up front?" } },
      { node: "tools", lane: "plan", kind: "allow", label: "request_money → jordan paid up front",
        chat: { from: "jordan", text: "deposit sent 👍 (shocking, I know)" } },
      { node: "gate", lane: "plan", kind: "modify", label: "gate: MODIFY + ASK book — rule r1 moved Sam to refundable",
        detail: { kind: "json", title: "Decision · action=ask after modify · rule r1", value: {
            final_args: { non_refundable_for: ["priya", "jordan"], refundable_for: ["sam"], total_usd: 378 },
            reason: "spend $378 is over the $100 auto-spend cap",
          }, note: "exposure $240 fits under the $300 cap. The agent never asked for the refundable ticket — the learned rule rewrote the call, then the auto-spend cap sent the amount to Alex." },
        approval: { id: "ap3", tool: "book", question: "Approve book $378 — Sam refundable, $240 non-refundable on Priya and Jordan?" } },
      { node: "tools", lane: "plan", kind: "allow", label: "book → confirmed under taco-council:v2",
        chat: { from: "flake", card: { title: "Booked · Pacifica beach house", lines: ["Sat 17 Oct · 4 guests", "$378 charged · Sam refundable (+$18 premium)", "Under v2 · approved by Alex"], tone: "receipt" } } },
      { node: "agent", lane: "plan", kind: "allow", label: "finish_plan — ep_007 booked under v2 (canary trial plan)" },
    ],
  },
  {
    id: "tick2",
    title: "Advance / evaluate",
    subtitle: "Canary verdict on v2",
    policy: { label: "v2", status: "canary" },
    events: [
      { node: "tools", lane: "learn", kind: "info", label: "simulator.tick(7) — Sam bails again",
        chat: { from: "sam", text: "so sorry, something came up 🙃" } },
      { node: "outcomes", lane: "learn", kind: "db", label: "episodes.update_one ep_007 — status resolved",
        detail: { kind: "json", title: "outcomes", value: { bailed: ["sam"], showed: ["priya", "jordan"], total_cost_usd: 18, paid_late_days: { jordan: 0, priya: 0 } },
          note: "Sam bailed on a $120 share and it cost $18 — the refundable premium, not the seat." },
        chat: { from: "system", text: "Plan resolved · $18 lost (refundable premium) · everyone paid on time" } },
      { node: "policy", lane: "learn", kind: "promote", label: "canary.evaluate → promoted",
        detail: { kind: "table", head: ["measure", "value"], rows: [
          ["incumbent v1 expected cost", "$124.29"],
          ["realized cost under v2", "$18.00"],
          ["verdict", "promoted"],
        ], note: "expected_cost() prices the same plan under v1: Sam 0.75 × $120 + Priya and Jordan 0.13 × $120. Realized ≤ expected, so v2 becomes active and v1 is superseded." },
        chat: { from: "flake", text: "v2 passed its trial: $18 realized against $124 expected under the old policy. v2 is now active." } },
    ],
    policyAfter: { label: "v2", status: "active" },
  },
  {
    id: "reckless",
    title: "Reckless Retro",
    subtitle: "A bad proposal, rejected by its own backtest",
    policy: { label: "v2", status: "active" },
    events: [
      { node: "proposal", lane: "learn", kind: "model", label: "retro.RECKLESS — drop the rules, keep the premiums",
        detail: { kind: "json", title: "PolicyProposal (scripted bad actor)", value: {
            rules: [], guardrails: { max_nonrefundable_exposure_usd: 300, max_auto_spend_usd: 100, min_expected_attendance_ratio: 0.6, min_confidence: 0.75 },
            auto_book_nonrefundable: true, similar_plans_k: 1,
            rationale: "Drop the refundable rules and save the premiums.",
          }, note: "Caps sit exactly on the floors, so the constitution has nothing to clamp. The backtest has to catch this one." } },
      { node: "backtest", lane: "learn", kind: "reject", label: "backtest.run — 7 episodes, delta −$327.00 → reject",
        detail: { kind: "table", head: ["measure", "value"], rows: [
          ["baseline (v2 rules)", "$118.00"],
          ["proposed (no rules)", "$445.00"],
          ["delta", "−$327.00"],
          ["accepted rules", "0"],
        ], note: "Replaying history without the refundable rule puts Sam's bailed shares straight back on the bill." } },
      { node: "policy", lane: "learn", kind: "reject", label: "versions.create → taco-council:v3 status rejected",
        detail: { kind: "table", head: ["version", "status", "rules", "exposure cap", "auto spend", "backtest"], rows: [
          ["taco-council:v1", "superseded", "0", "0", "0", "-"],
          ["taco-council:v2", "active", "3", "300", "100", "225.0"],
          ["taco-council:v3", "rejected", "0", "300", "100", "-327.0"],
        ], note: "v3 is stored, not applied. The policy history is the audit trail: proposed, measured, refused." },
        chat: { from: "flake", text: "A proposal to drop the refundable rules failed its backtest by $327. Recorded as v3, rejected. v2 stays active." } },
    ],
  },
];
